### ISSUE TITLE
Submit a PR to get this into Package Control instead of mkleehammer's old repo?

### ISSUE THREAD

**Issue by dtjohnso** [kublaios/dired#2]
I've been using this repo since @mkleehammer stopped hosting his version. 

I see he's submitted a PR to have this removed from Package Control: https://github.com/wbond/package_control_channel/pull/7326

The instructions for [submitting to Package Control are here](https://packagecontrol.io/docs/submitting_a_package). I'd do it myself, except I'm not 100% sure I can run the tests properly on my system (I've never built a package myself). 

Anyone out there who'd be willing/able to submit a PR to Package Control to get this in there?

**Comment by FichteFoll** [comment]
I redirected the original entry to this fork.

**Comment by dtjohnso** [comment]
I was able to reinstall from this fork using Package Control today. Thanks for the fix @FichteFoll.
